/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/earth/earth_scene.gltf --transform --keepmeshes, -j --keepmaterials, -M 
Files: public/earth/earth_scene.gltf [7.73KB] > /mnt/A05876CC5876A0A8/Business/Dev/3d-developer-portfolio csr test/earth_scene-transformed.glb [137.61KB] (-1680%)
Author: ABOD.ANIMATION (https://sketchfab.com/body3d2005)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-c2e4294c32ea4d8b850e152fc26aeeb4
Title: earth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earth_scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, -0.262]} />
    </group>
  )
}

useGLTF.preload('/earth_scene-transformed.glb')
